<a href="https://colab.research.google.com/github/AndriuGJ/Colab/blob/main/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy, libreria de ciencia de datos

In [1]:
import numpy as np


Array de 1 dimension

In [2]:
array_id = np.array([10,20,30])
print(array_id)

[10 20 30]


Array de 2 dimensiones

In [3]:
array_2d = np.array([(10,20,30),(50,60,70)])
array_2d

array([[10, 20, 30],
       [50, 60, 70]])

Array de 3 dimensiones

In [7]:
array_3d=np.array([(10,20,30),(40,50,60),(70,80,90)],dtype=float)
array_3d

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

Array con ceros de 3 filas y 4 columnas

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


ARRAY DE UNOS CON 2 DIMENSIONES DE 4 FILAS 5 COLUMNAS

In [11]:
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

ARRAYS INTERVALOS Y SALTOS

In [20]:
np.arange(15,30,2)

array([15, 17, 19, 21, 23, 25, 27, 29])

ARRAYS CON INTERVALOS Y DIVISIONES

In [23]:
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

ARRAYS CON VALORES DADOS

In [26]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

ARRAY CON MATRIZ IDENTIDAD, DIAGONAL DE UNOS

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

ARRAYS VALORES ALEATORIOS

In [48]:
#Valores aleatorios de 0 y 1
np.random.random((3,2))

array([[0.63240772, 0.31680507],
       [0.22444027, 0.14833681],
       [0.6158473 , 0.93573624]])

ARRAY DE NUMEROS VACIOS

In [49]:
#ARRAY DE NUEMEROS VACIOS DE 4 X 3
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

GRABAR Y CARGAR

In [62]:
#Grabar
np.save('mi_array_2d', array_2d)

In [65]:
#cargar
mi_array=np.load('mi_array_2d.npy')
mi_array

array([[10, 20, 30],
       [50, 60, 70]])

GRABAR Y CARGAR FICHEROS DE TEXTO

In [66]:
#Grabar texto
np.savetxt('mi_array_2d.txt',array_2d,delimiter=" ")

In [67]:
#Cargar
np.loadtxt('mi_array_2d.txt')

array([[10., 20., 30.],
       [50., 60., 70.]])